name: actions

on:
  push:
    branches:
      - main

jobs:
  build-qiniu:
    if: secrets.build == 'qiniu'
    runs-on: ubuntu-latest
    env:
        prefixhost: ${{ secrets.PREFIXHOST }}
        accessKey: ${{ secrets.ACCESSKEY }}
        secretKey: ${{ secrets.SECRETKEY }}
        space: ${{ secrets.SPACE }}
        zone: ${{ secrets.ZONE }}
    steps:
      # 拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build-qiniu
  build-server:
    if: secrets.build != 'qiniu'
    runs-on: ubuntu-latest
    env:
        host: ${{secrets.host}}
        username: ${{secrets.username}}
        password: ${{secrets.password}}
        port: ${{secrets.port}}
        remote_path: ${{secrets.remote_path}}
        end_cmd: ${{secrets.end_cmd}}
    steps:
      # 拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build-server