name: actions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
        build: ${{ secrets.build }}
        prefixhost: ${{ secrets.PREFIXHOST }}
        accessKey: ${{ secrets.ACCESSKEY }}
        secretKey: ${{ secrets.SECRETKEY }}
        space: ${{ secrets.SPACE }}
        zone: ${{ secrets.ZONE }}
        host: ${{secrets.host}}
        username: ${{secrets.username}}
        password: ${{secrets.password}}
        port: ${{secrets.port}}
        remote_path: ${{secrets.remote_path}}
        end_cmd: ${{secrets.end_cmd}}
    steps:
      # 拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: build-qiniu
        if: ${{ env.build == 'qiniu' }}
        run: |
          npm install
          npm run build-qiniu
      - name: build-server
        if: ${{ env.build != 'qiniu' }}
        run: |
          npm install
          npm run build-server
      - name: 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.value}}
          release_name: v${{steps.version.outputs.value}}
          body: ${{steps.description.outputs.content}}
          draft: false
          prerelease: fals

