name: actions

on: [push, pull_request] # 触发事件

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        prefixhost: ${{ secrets.PREFIXHOST }}
        accessKey: ${{ secrets.ACCESSKEY }}
        secretKey: ${{ secrets.SECRETKEY }}
        space: ${{ secrets.SPACE }}
        zone: ${{ secrets.ZONE }}
    steps:
      # 拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run node ./qiniu.js
