name: actions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
        build: ${{ secrets.build }}
        prefixhost: ${{ secrets.PREFIXHOST }}
        accessKey: ${{ secrets.ACCESSKEY }}
        secretKey: ${{ secrets.SECRETKEY }}
        space: ${{ secrets.SPACE }}
        zone: ${{ secrets.ZONE }}
        host: ${{secrets.host}}
        username: ${{secrets.username}}
        password: ${{secrets.password}}
        port: ${{secrets.port}}
        remote_path: ${{secrets.remote_path}}
        end_cmd: ${{secrets.end_cmd}}
    steps:
      # 拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: build-qiniu
        if: ${{ env.build == 'qiniu' }}
        run: |
          npm install
          npm run build-qiniu
      - name: build-server
        if: ${{ env.build != 'qiniu' }}
        run: |
          npm install
          npm run build-server
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: 创建GitHub Release
        if: ${{ env.build != 'qiniu' }}
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: latest
          release_name: latest
          body: 管理面板前端
          draft: false
          prerelease: false
      - name: 上传包到GitHub Release
        if: ${{ env.build != 'qiniu' }}
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip

