name: actions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
        build: ${{ secrets.build }}
        prefixhost: ${{ secrets.PREFIXHOST }}
        accessKey: ${{ secrets.ACCESSKEY }}
        secretKey: ${{ secrets.SECRETKEY }}
        space: ${{ secrets.SPACE }}
        zone: ${{ secrets.ZONE }}
        host: ${{secrets.host}}
        username: ${{secrets.username}}
        password: ${{secrets.password}}
        port: ${{secrets.port}}
        remote_path: ${{secrets.remote_path}}
        end_cmd: ${{secrets.end_cmd}}
    steps:
      # 拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: build-qiniu
        if: ${{ env.build == 'qiniu' }}
        run: |
          npm install
          npm run build-qiniu
      - name: build-server
        if: ${{ env.build != 'qiniu' }}
        run: |
          npm install
          npm run build-server
      - name: 上传包到GitHub Release
        if: ${{ env.build != 'qiniu' }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip

